# Colab を電卓として使ってみる


# 四則演算
セルに**式**だけを書くと，それを**評価**した結果（計算結果）が出力される．

In [1]:
1+2+3+4+5+6+7+8+9+10 

55

In [2]:
1-2+3-4+5-6+7-8+9-10

-5

１つのセルに２つ以上の式を書くと，最後の式の**評価結果**だけが出力される．下記の例では，１つ目の計算式は**評価**自体は実行されるが，その結果は出力されないので，ちょっと無駄（計算はするが答案用紙に答を書かないのと同じ）．

In [3]:
1+2+3+4+5+6+7+8+9+10 # セルの最後ではないので，この計算結果は表示されない
1-2+3-4+5-6+7-8+9-10 # こちらの計算結果のみが出力される

-5

1つのセル内で複数計算を出力させたい場合は，それぞれの計算式を [`print`という**関数**](https://docs.python.org/3/library/functions.html#print)に渡す．

In [4]:
# 1つのセル内で複数の計算をする場合
print(1+2+3+4+5+6+7+8+9+10)
print(1-2+3-4+5-6+7-8+9-10)

55
-5


`print`関数の代表的な書式は以下のようになっており，それぞれの **引数** を順番に画面に出力する．引数としては，任意の**オブジェクト**（変数，文字列，式など）を取ることができる．
```python
print(引数1, 引数2, ...)
```
例えば，次の行：
```python
print( "a+b=", a+b ) # 和
```
は，`print`関数の第1引数として`"a+b="`という**文字列**，第2引数として`a+b`という**式**を与えている． `print`関数の引数に**式**が与えられた場合は，それを**評価した結果**(計算結果)が表示される． 最後の `# 和` というのは**コメント**．Python では `#` という記号から行末まではすべてコメントとして取り扱われる．

次のセルでは，`a` と`b` という2つの**変数**に値を**代入**し，その加減乗除を行った結果を [`print` **関数**](https://docs.python.org/3/library/functions.html#print)に渡している． 第1回講義の「Colaboratoryの練習」では整数の商を求めるのに [`int`**関数**](https://docs.python.org/3/library/functions.html#int) を使ったが， 整数の商を求める `//` という **演算子**があるので，これを使った方がスッキリと記述できてよい．

In [5]:
a = 13
b = 5
print( "a+b=", a+b ) # 和
print( "a-b=", a-b ) # 差
print( "b-a=", b-a ) # 差
print( "a*b=", a*b ) # 積
print( "a**b=", a**b ) # べき乗
print( "a//b=", a//b ) # 商
print( "a%b=", a%b ) # 剰余
print( "b//a=", b//a ) # 商
print( "b%a=", b%a ) # 剰余


a+b= 18
a-b= 8
b-a= -8
a*b= 65
a**b= 371293
a//b= 2
a%b= 3
b//a= 0
b%a= 5


なお，除算の結果を実数で求めたい場合は，`//` の代わりに `/` という **演算子** を使う．

In [6]:
a = 13
b = 5
print( "a//b=", a//b ) # 商
print( "b//a=", b//a ) # 商
print( "a/b=", a/b ) # 除算
print( "b/a=", b/a ) # 除算


a//b= 2
b//a= 0
a/b= 2.6
b/a= 0.38461538461538464


# `math` モジュールを用いた高度な演算
[`math` モジュール](https://docs.python.org/3/library/math.html)を用いれば，更に高度な演算も行える．

Python では虚数単位は `j` で表示される．例えば，$4+2i$ はPythonでは `4+2j` で表されるし，単位虚数$i$ は `1j` で表される．なお，この講義では，複素数は取り扱わない．

In [7]:
import math # math モジュールをインポートする
import cmath # 複素数用数学関数

In [8]:
print(math.factorial(10)) # 10の階乗（10!)
print(math.gcd(24,56)) # 最大公約数
print(math.exp(0.7)) # 指数
print(math.log(2)) # 自然対数
print(math.log10(400)) # 10を底とする対数
print(math.pow(4, 1/3)) # べき乗（4の1/3乗を返す）
print(math.sqrt(12)) # 平方根
print(cmath.exp(1j*math.pi).real) # 世界で最も美しい数式（実部のみ表示）

3628800
8
2.0137527074704766
0.6931471805599453
2.6020599913279625
1.5874010519681994
3.4641016151377544
-1.0


In [9]:
cmath.exp(1j*math.pi)

(-1+1.2246467991473532e-16j)

# `numpy` モジュールを用いたベクトル・行列演算
[`numpy` モジュール](https://docs.scipy.org/doc/numpy/)を用いれば，ベクトル・行列の高速演算が行える．

慣習的に`numpy` モジュールをインポートする時は，

```python
import numpy as np
```

として，`np` という**別名**を使うことが多い．

In [10]:
import numpy as np # numpy モジュールを np という別名でインポート

[`numpy.array`関数](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)を使ってベクトル，行列を定義できる．

In [11]:
A = np.array([[3, 2, 8], 
              [0, 4, 3],
              [5, 0, 1]
              ]) # 3x3正方行列
B = np.array([[1, 3, 2, 5],
              [2, 1, 0, 6],
              [7, 4, 3, 0]
              ]) # 3行4列行列
b = np.array([1, 2, 3]) # 3次元ベクトル

print("A:\n", A) # 行列A
print("B:\n", B) # 行列B
print("b:\n", b) # 1次元ベクトルb

A:
 [[3 2 8]
 [0 4 3]
 [5 0 1]]
B:
 [[1 3 2 5]
 [2 1 0 6]
 [7 4 3 0]]
b:
 [1 2 3]


行列`A` の転置は `A.T` で表される．行列同士の積や行列とベクトルの積は [`numpy.dot`関数](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)を使って求められる．

行列に対して `*` という演算子を使うと，行列の積（内積）ではなく「各要素ごとの積」を計算してしまうので注意．



In [12]:
print( B.T ) # 行列Bの転置
print( A.dot(b) ) # 行列Aとbの積
print( B.T.dot(A) ) # Bの転置とAの積
print( A.dot(A) ) # 行列Aと行列Aの積
print( A*A ) # 行列Aの要素ごとの積

[[1 2 7]
 [3 1 4]
 [2 0 3]
 [5 6 0]]
[31 17  8]
[[38 10 21]
 [29 10 31]
 [21  4 19]
 [15 34 58]]
[[49 14 38]
 [15 16 15]
 [20 10 41]]
[[ 9  4 64]
 [ 0 16  9]
 [25  0  1]]


[`numpy.linalg.inv`関数](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)や[`numpy.linalg.eig`関数](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html)を用いれば，逆行列や固有値・固有ベクトルもあっという間に計算できる．

In [13]:
invA = np.linalg.inv(A)
print( invA ) # 行列Aの逆行列
# 正しく逆行列が求められているかどうかを確認
print( invA.dot(A) ) # 行列Aの逆行列と元の行列の積（計算誤差を除けばほぼ単位行列）
np.set_printoptions(suppress=True) # 指数表示をやめる
print( invA.dot(A) ) # 単位行列が表示される
print( A.dot(invA) ) # 逆行列を右から乗じても同じく単位行列が得られる

[[-0.03389831  0.01694915  0.22033898]
 [-0.12711864  0.31355932  0.07627119]
 [ 0.16949153 -0.08474576 -0.10169492]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.16333634e-17  1.00000000e+00  4.16333634e-17]
 [-5.55111512e-17  0.00000000e+00  1.00000000e+00]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
w, v = np.linalg.eig(A) # 行列Aの固有値・固有ベクトル
print(w) # 固有値の表示
print(v) # 固有ベクトル（各列が各固有値に対応した，長さを1に基準化した固有ベクトル）
# 正しく固有ベクトルが求められているかどうかを確認
p = A.dot(v[:,0]) # 行列Aと1番目の固有ベクトル（vの第0列）を乗じたもの
q = w[0]*v[:,0] # 1番目固有値（wの第0要素）と対応する固有ベクトルの積
print(p)
print(q)
print(p-q) # 殆どゼロ

[-4.10734405  8.86755146  3.23979259]
[[ 0.69177452 -0.80133248  0.10937574]
 [ 0.2506006  -0.31387293 -0.96354577]
 [-0.67723508 -0.50926421  0.24416488]]
[-2.84135594 -1.02930287  2.78163749]
[-2.84135594 -1.02930287  2.78163749]
[-0. -0.  0.]


In [15]:
w, v = np.linalg.eig(A) # 行列Aの固有値・固有ベクトル
print(w) # 固有値の表示
print(v) # 固有ベクトル（各列が各固有値に対応した，長さを1に基準化した固有ベクトル）
# 正しく固有ベクトルが求められているかどうかを確認
p = A.dot(v[:,2]) # 行列Aと1番目の固有ベクトル（vの第0列）を乗じたもの
q = w[2]*v[:,2] # 1番目固有値（wの第0要素）と対応する固有ベクトルの積
print(p)
print(q)
print(p-q) # 殆どゼロ

[-4.10734405  8.86755146  3.23979259]
[[ 0.69177452 -0.80133248  0.10937574]
 [ 0.2506006  -0.31387293 -0.96354577]
 [-0.67723508 -0.50926421  0.24416488]]
[ 0.3543547  -3.12168846  0.79104357]
[ 0.3543547  -3.12168846  0.79104357]
[-0.  0. -0.]


2番め，3番目の固有値と固有ベクトルについても，正しく計算できていることを確認しよう．

In [ ]:
# 実はこうすれば一度に確認できる
p = A.dot(v) 
q = w*v 
p - q

NameError: ignored

上のセルの解説．

行列$\mathbf{A}$の固有値$w_{0}, w_{1}, w_{2}\in \mathcal{R}$ のそれぞれに対応する固有ベクトル(それぞれ3次元列ベクトル）を$\mathbf{v}_{0}, \mathbf{v}_{1}, \mathbf{v}_{2} \in \mathcal{R}^{3\times1}$ とし， それを並べたものを
$$\begin{align}
\mathbf{w} &= \begin{bmatrix} w_{0} & w_{1} & w_{2} \end{bmatrix}\\
\mathbf{V} &= \begin{bmatrix} \mathbf{v}_{0} & \mathbf{v}_{1} & \mathbf{v}_{2}\end{bmatrix}
\end{align}$$
とする． $\mathbf{w}$は3次元行ベクトル，$\mathbf{V}$は3×3正方行列である．

```python
w, v = np.linalg.eig(A)
``` 

という命令によって得られる`w`　および`v`は，それぞれ，上述の$\mathbf{w}$および$\mathbf{V}$に相当する．

ここで，
$$\begin{align}
\mathbf{A} \mathbf{V} &= \begin{bmatrix}
\mathbf{A} \mathbf{v}_{0} &
\mathbf{A} \mathbf{v}_{1} &
\mathbf{A} \mathbf{v}_{2}
\end{bmatrix} 
&&= \mathtt{p}
\\
&= \begin{bmatrix}
w_{0} \mathbf{v}_{0} &
w_{1} \mathbf{v}_{1} &
w_{2} \mathbf{v}_{2}
\end{bmatrix} &&= \mathtt{q}
\end{align}
$$
とした時，それぞれは， `numpy` の文法では
```python
p = A.dot(v)
q = w*v
```
と表される（`.dot` がベクトル・行列の積を表すのに対し，`*`が要素ごとの積を表すことに注意されたい）．このため，`p-q` はゼロ行列となる．